draw_config:
  dark_mode: false

  svg_extra_style: |
    svg.keymap {
      background-color: #eeeeee;
      font-family: Inter, sans-serif;
      fill: #24292e;
    }

    rect.key {
      fill: #ffffff;
    }

    rect.key,
    rect.combo {
      stroke: #c9cccf;
      stroke-width: 1;
    }

parse_config:
  raw_binding_map:
    # Shift
    "&kp LEFT_SHIFT": "⇧"
    "&kp LC(LEFT_SHIFT)": "⌃⇧"
    "&kp LA(LEFT_SHIFT)": "⌥⇧"
    "&kp LG(LEFT_SHIFT)": "⌘⇧"
    "&kp RIGHT_SHIFT": "⇧"
    "&kp RC(RIGHT_SHIFT)": "⌃⇧"
    "&kp RA(RIGHT_SHIFT)": "⌥⇧"
    "&kp RG(RIGHT_SHIFT)": "⌘⇧"

    # Option
    "&kp LEFT_ALT": "⌥"
    "&kp RC(LEFT_ALT)": "⌃⌥"
    "&kp RA(LEFT_ALT)": "⌥⌥"
    "&kp RG(LEFT_ALT)": "⌘⌥"
    "&kp RIGHT_ALT": "⌥"
    "&kp RC(RIGHT_ALT)": "⌃⌥"
    "&kp RA(RIGHT_ALT)": "⌥⌥"
    "&kp RG(RIGHT_ALT)": "⌘⌥"

    # Control
    "&kp LEFT_CONTROL": "⌃"
    "&kp RC(LEFT_CONTROL)": "⌃⌃"
    "&kp RA(LEFT_CONTROL)": "⌃⌥"
    "&kp RG(LEFT_CONTROL)": "⌃⌘"
    "&kp RIGHT_CONTROL": "⌃"
    "&kp RC(RIGHT_CONTROL)": "⌃⌃"
    "&kp RA(RIGHT_CONTROL)": "⌃⌥"
    "&kp RG(RIGHT_CONTROL)": "⌃⌘"

    # Command
    "&kp LEFT_GUI": "⌘"
    "&kp RC(LEFT_GUI)": "⌃⌘"
    "&kp RA(LEFT_GUI)": "⌥⌘"
    "&kp RG(LEFT_GUI)": "⌘⌘"

    "&kp RIGHT_GUI": "⌘"
    "&kp RC(RIGHT_GUI)": "⌃⌘"
    "&kp RA(RIGHT_GUI)": "⌥⌘"
    "&kp RG(RIGHT_GUI)": "⌘⌘"

    "&kp LEFT_WIN": "⌘"
    "&kp RC(LEFT_WIN)": "⌃⌘"
    "&kp RA(LEFT_WIN)": "⌥⌘"
    "&kp RG(LEFT_WIN)": "⌘⌘"

    "&kp RIGHT_WIN": "⌘"
    "&kp RC(RIGHT_WIN)": "⌃⌘"
    "&kp RA(RIGHT_WIN)": "⌥⌘"
    "&kp RG(RIGHT_WIN)": "⌘⌘"

    # Macグローブキー
    "&kp GLOBE": "🌐"

    # Enter
    "&kp ENTER": "⏎"

    # Media Keys
    "&kp C_PLAY_PAUSE": "⏯"
    "&kp C_PREVIOUS": "⏮"
    "&kp C_NEXT": "⏭"

    # Backspace
    "&kp BACKSPACE": "⌫"

    # Tab
    "&kp TAB": "⇥"
    "&kp LC(TAB)": "⌃⇥"
    "&kp LA(TAB)": "⌥⇥"
    "&kp LG(TAB)": "⌘⇥"

    # Caps Lock
    "&kp CAPSLOCK": "⇪"

    # Delete
    "&kp DELETE": "⌦"

    # Arrows
    "&kp RIGHT": "→"
    "&kp LEFT": "←"
    "&kp UP": "↑"
    "&kp DOWN": "↓"

    # Mod-Tap
    "&mt LEFT_SHIFT Z":
      t: "Z"
      h: "⇧"

    "&mt RIGHT_SHIFT SLASH":
      t: "/"
      h: "⇧"
    
    # Control + 矢印
    "&kp LC(LEFT)": "⌃←"
    "&kp LC(RIGHT)": "⌃→"
    "&kp LC(UP)": "⌃↑"
    "&kp LC(UP_ARROW)": "⌃↑"
    "&kp LC(DOWN)": "⌃↓"

    # Option + 矢印
    "&kp LA(LEFT)": "⌥←"
    "&kp LA(RIGHT)": "⌥→"
    "&kp LA(UP)": "⌥↑"
    "&kp LA(DOWN)": "⌥↓"

    # Command + 矢印
    "&kp LG(LEFT)": "⌘←"
    "&kp LG(LEFT_ARROW)": "⌘←"
    "&kp LG(RIGHT)": "⌘→"
    "&kp LG(RIGHT_ARROW)": "⌘→"
    "&kp LG(UP)": "⌘↑"
    "&kp LG(DOWN)": "⌘↓"

    # Shift + 矢印
    "&kp LS(LEFT)": "⇧←"
    "&kp LS(RIGHT)": "⇧→"
    "&kp LS(UP)": "⇧↑"
    "&kp LS(DOWN)": "⇧↓"

  # LC()、LA()、LG()、LS()内の修飾キー表記
  modifier_fn_map:
    left_ctrl: "⌃"
    right_ctrl: "⌃"
    left_shift: "⇧"
    right_shift: "⇧"
    left_alt: "⌥"
    right_alt: "⌥"
    left_gui: "⌘"
    right_gui: "⌘"
    left_arrow: "←"
    right_arrow: "→"
    up_arrow: "↑"
    down_arrow: "↓"
    enter: "⏎"

    # 例：LC(LA(E)) → ⌃⌥E
    keycode_combiner: "{mods}{key}"
    mod_combiner: "{mod_1}{mod_2}"

    special_combinations:
      left_ctrl+left_alt+left_gui+left_shift: "✦"
      left_ctrl+left_alt+left_shift: "Meh"