draw_config:
  dark_mode: false

  svg_extra_style: |
    svg.keymap {
      background-color: #eeeeee;
      font-family: Inter, sans-serif;
      fill: #24292e;
    }

    rect.key {
      fill: #ffffff;
    }

    rect.key,
    rect.combo {
      stroke: #c9cccf;
      stroke-width: 1;
    }

parse_config:
  raw_binding_map:
    # Shift
    "&kp LEFT_SHIFT": "⇧"
    "&kp RIGHT_SHIFT": "⇧"

    # Option
    "&kp LEFT_ALT": "⌥"
    "&kp RIGHT_ALT": "⌥"

    # Control
    "&kp LEFT_CONTROL": "⌃"
    "&kp RIGHT_CONTROL": "⌃"

    # Command
    "&kp LEFT_GUI": "⌘"
    "&kp RIGHT_GUI": "⌘"
    "&kp LEFT_WIN": "⌘"
    "&kp RIGHT_WIN": "⌘"

    # Macグローブキー
    "&kp GLOBE": "🌐"

    # Enter
    "&kp ENTER": "⏎"

    # Arrows
    "&kp RIGHT": "→"
    "&kp LEFT": "←"
    "&kp UP": "↑"
    "&kp DOWN": "↓"

    # Mod-Tap
    "&mt LEFT_SHIFT Z":
      t: "Z"
      h: "⇧"

    "&mt RIGHT_SHIFT SLASH":
      t: "/"
      h: "⇧"
    
    # Control + 矢印
    "&kp LC(LEFT)": "⌃←"
    "&kp LC(RIGHT)": "⌃→"
    "&kp LC(UP)": "⌃↑"
    "&kp LC(UP_ARROW)": "⌃↑"
    "&kp LC(DOWN)": "⌃↓"

    # Option + 矢印
    "&kp LA(LEFT)": "⌥←"
    "&kp LA(RIGHT)": "⌥→"
    "&kp LA(UP)": "⌥↑"
    "&kp LA(DOWN)": "⌥↓"

    # Command + 矢印
    "&kp LG(LEFT)": "⌘←"
    "&kp LG(LEFT_ARROW)": "⌘←"
    "&kp LG(RIGHT)": "⌘→"
    "&kp LG(RIGHT_ARROW)": "⌘→"
    "&kp LG(UP)": "⌘↑"
    "&kp LG(DOWN)": "⌘↓"

    # Shift + 矢印
    "&kp LS(LEFT)": "⇧←"
    "&kp LS(RIGHT)": "⇧→"
    "&kp LS(UP)": "⇧↑"
    "&kp LS(DOWN)": "⇧↓"

  # LC()、LA()、LG()、LS()内の修飾キー表記
  modifier_fn_map:
    left_ctrl: "⌃"
    right_ctrl: "⌃"
    left_shift: "⇧"
    right_shift: "⇧"
    left_alt: "⌥"
    right_alt: "⌥"
    left_gui: "⌘"
    right_gui: "⌘"

    # 例：LC(LA(E)) → ⌃⌥E
    keycode_combiner: "{mods}{key}"
    mod_combiner: "{mod_1}{mod_2}"

    special_combinations:
      left_ctrl+left_alt+left_gui+left_shift: "✦"
      left_ctrl+left_alt+left_shift: "Meh"