name: Draw ZMK keymaps

on:
  workflow_dispatch:
  push:
    paths:
      - "config/*.keymap"
      - "config/*.json"
      - "config/*.dtsi"
      - "keymap_drawer.config.yaml"
      - ".github/workflows/draw-keymaps.yml"

jobs:
  draw:
    uses: caksoylar/keymap-drawer/.github/workflows/draw-zmk.yml@main
    permissions:
      contents: write
    with:
      keymap_patterns: "config/bb_40.keymap"
      json_path: "config"
      config_path: "keymap-drawer/config.yaml"
      output_folder: "keymap-drawer"
      parse_args: ""
      draw_args: ""
      fail_on_error: true
